### ISSUE TITLE
Memory leak with image-related functions

### ISSUE THREAD

**Issue by beornlake** [Spawnova/ShinsOverlayClass#19]
It appears as though there is a memory leak related to the image-relation functions in `ShinsOverlayClass`.

To repro:
```autohotkey
; instantiate new SOC
overlay := new ShinsOverlayClass()

; do something with an image
overlay.GetImageDimensions(...)
; or...
overlay.DrawImage(...)

; free the SOC object
overlay.__Delete()  ; this is needed because the overlay is not released to garbage collection in the next step
overlay := ""
```
After these steps (in my particular use) the memory footprint of the AHK script has increased by ~8 MB, and it grows by that amount _every time_ a new `ShinsOverlayClass` uses the image functions. That memory is never released back to the OS, and in certain circumstances it can cause a huge memory leak until the script is reloaded.

Note that simply calling `overlay := ""` does not allow the object to be properly released for garbage collection, which may be related to this leak.

**Comment by Spawnova** [comment]
This should be solved with the update tomorrow, when you try it then please let me know if it's solved on your end as well

**Comment by beornlake** [comment]
Hmm... I'm still seeing a 1-to-1.5 MB memory leak per instantiation when calling image functions, but it's definitely an improvement.

**Comment by Spawnova** [comment]
I'm not sure what would be causing that, I'm not able to replicate on my end at least, I'll continue to look into it though

Also the class was designed to only be instantiated once then ran in a main loop, the BeginDraw() function automatically handles situations where the target process changes size/pos/focus
```ahk
loop {
	if (overlay.BeginDraw()) {
		;...
		overlay.EndDraw()
	} else {
		sleep 10 
	}
}
```
Obviously you can use it however you want though, and for certain projects using it differently is the best approach, but generally if you can avoid creating new instances it performs better

Either way, I appreciate the feedback and bug reports, if you run into any more or have feature requests let me know, and I'll continue to look into this leaking issue

**Comment by beornlake** [comment]
Yeah, my use case is a little different because I'm using it only occasionally to draw an overlay on top of some applications, then it goes unused for hours (or maybe even days?). It gets created as a child object of a parent object in my code, then gets cleaned up when that parent object goes away. This method had been working fine until the recent updates, so maybe it's partly my fault for using SOC in a manner that is different than prescribed! I appreciate you working on these bugs, though!

In the latest version, I'm having a hard-to-diagnose crash when releasing the SOC class. Sometimes it happens on the first release, sometimes it's after 15 cycles, but eventually the parent AHK app silently crashes with a brief spinning wheel on the mouse and then *poof* the app is gone.
- This does not happen in fa32b81ad00738b5d115029f3a7cdb8903b1e5ed, so it's related to the memory leak fix.
- It only happens when I'm drawing text or images. If I just do some simple line-drawing calls, the crash doesn't happen.

https://www.autohotkey.com/docs/v1/lib/DllCall.htm#except might be helpful here?

(Also, I apologize for not being able to more helpfully debug and offer Pull Requests. I haven't been able to fully wrap my head around the vTable method in the code, so I don't feel comfortable poking around in the source just yet.)

**Comment by Spawnova** [comment]
I see, that's likely related to freeing the image or text resources, I don't see anything obvious that would cause an issue there, but I'll write some test scripts later and see if I can't figure it out
for the meantime, I would suggest just having a toggle for the overlay which should mimic the same results but without having to create all the resources every time

here is an example on how to do that, calling ToggleOverlay will handle enabling/disabling it, then you can just draw as normal
```ahk
#include <shinsoverlayclass>

#requires autohotkey v1+

;ToggleOverlay(overlay,0) ;calling toggle with 0 can create the initial instance without displaying it

f1::
ToggleOverlay(overlay) ;toggle overlay on/off

if (overlay.data.toggle) { ;if it's active then draw the scene
	if (overlay.begindraw()) {

		overlay.drawtext("Now = " a_now,10,10,40)
		overlay.FillRectangle(0,0,100,100,0x77FF0000)
		overlay.DrawRectangle(0,0,100,100,0xFF000000)
		
		overlay.enddraw()
	}
}
return

ToggleOverlay(byref o,force:=-1) {
	if (!IsObject(o)) { ;if first time, create the instance
		o := new ShinsOverlayClass("Untitled - Paint")
		o.data.toggle := (force >= 0 ? force : 1)
		if (force = 0)
			o.Display(0)
	} else { ;if instance already exists, then toggle it's active state
		o.Clear()
		o.data.toggle := (force >= 0 ? force : !o.data.toggle)
		o.Display(o.data.toggle) ;sets the window display, visible or hidden
	}
}
```

**Comment by beornlake** [comment]
Yeah, I'll need to spend some time rearchitecting the app. It'd be nice to have the crash figured out, though!
